-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 15:19:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema putevka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema putevka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `putevka` DEFAULT CHARACTER SET utf8 ;
USE `putevka` ;

-- -----------------------------------------------------
-- Table `putevka`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `putevka`.`route` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `climate` VARCHAR(45) NOT NULL,
  `duration` DATETIME NOT NULL,
  `hotel` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `putevka`.`putevka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `putevka`.`putevka` (
  `id` INT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `quantity` INT NOT NULL,
  `discount` INT NOT NULL,
  `idRoute` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `route_id_idx` (`idRoute` ASC) VISIBLE,
  CONSTRAINT `route_id`
    FOREIGN KEY (`idRoute`)
    REFERENCES `putevka`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `putevka`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `putevka`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `idPutevka` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `putevka_id_idx` (`idPutevka` ASC) VISIBLE,
  CONSTRAINT `putevka_id`
    FOREIGN KEY (`idPutevka`)
    REFERENCES `putevka`.`putevka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
